### ISSUE TITLE
Version tag missing

### ISSUE THREAD

**Issue by UffeJakobsen** [asmotor/asmotor-util#1]
Hi,

It would be nice if this (sub) project had a version tag to "lock" on to... for distribution packaging purposes...

Just grabbing master.tgz (HEAD) of asmotor-util - has the risk of using a misaligned asmotor-util with asmotor

anyway It would be nice with some sort of version tag on asmotor-util

/Uffe :-)

**Comment by csoren** [comment]
Good point. asmotor-util is meant to be used as a submodule, and should probably not be distributed by itself. Unfortunately GitHub's automatic tarballs do not include submodule sources.

As a workaround I have updated the out-of-date build scripts and have added an automated way to create releases. Will https://github.com/asmotor/asmotor/releases/tag/1.1.1 work for you? GitHub still insists on creating and publishing useless tarballs called "Source code", they should be ignored. There is no way to disable them, GitHub's handling of submodules is somewhat lacking.

**Comment by UffeJakobsen** [comment]
Hello,
Yes ! - that ensures that I get the right asmotor-util  - thanks
Another way would be to lock the versions together - but having to bump/sync the version om every module for every release - that is a tedious task.

You can see the "result" here https://aur.archlinux.org/packages/?K=asmotor

/Uffe :-)

**Comment by csoren** [comment]
Thank you for that. There's a small typo, it says 80x0 instead of 680x0. Keeping util versioning in sync with asmotor is not something I'd want to do. util doesn't change that often and it's also used by the xgbfix repository.

**Comment by UffeJakobsen** [comment]
Ups a copy-paste typo - it is fixed now - thanks :-)

Regarding asmotor-util: I agree inter-locking versions is not something that I would choose myself :-)

**Comment by UffeJakobsen** [comment]
BTW: if you can come up with a better package description - then please let me know :-)
